### ISSUE TITLE
Templating vs theming

### ISSUE THREAD

**Issue by adamhsparks** [AAGI-Org-AU-Public/AAGITemplates#8]
We can wrap everything into one package or we can keep going with two different ones as we now have.

It would be good to have that discussion at the next meeting.

I don't really have a preference as long as we clearly define our packages' scopes and stick to them.

**Comment by rogerssam** [comment]
Yeah good thoughts. No real preference from me either, so let's come up with a plan in the next meeting.

**Comment by RussellAndrewEdson** [comment]
Agreed. 

Also, I'm starting to wonder whether the dotx/potx templates shouldn't be in a separate repo as well. At the moment I have the install instructions in the README.md that retrieves them from this repo as a direct download, and they end up installed (but hidden) in the inst/ directory stuff for the R package. But they weren't really designed to be used with the R package at all--they're pure Word/PowerPoint templates for people that have that workflow (e.g., we have one statistician on the UA team that likes to work in Genstat, and copy/pastes rich-text and graphs from Genstat straight into word for her reports, which is the sort of workflow I had in mind when writing those templates). So it feels outside of scope for those word/ppt templates to be in here.

**Comment by adamhsparks** [comment]
@RussellAndrewEdson, that's a good point to discuss. There is scope with the RStudio add-ins, but if you use Postitron/VS Codium/VS Code or anything else, the "File > New > From Template" workflow isn't there for the Office documents.

**Comment by adamhsparks** [comment]
And from what I can tell, it's not supported for Quarto documents, just RMarkdown > Word

**Comment by rogerssam** [comment]
> And from what I can tell, it's not supported for Quarto documents, just RMarkdown > Word

Yeah correct. We discussed this in the previous meeting. The GUI workflow of `File > New Rmarkdown > From Template` doesn't work for Quarto, and only applies to Rstudio, which is why I originally wrote [the function](https://github.com/AAGI-Org-AU-Public/AAGITemplates/blob/master/R/new_report.R) to create the documents (we also have a couple of Emacs + ESS users). 

There's a chance that Quarto template support gets added to Rstudio, but with Positron now on the scene I'm not holding my breath. The issue has been open for a couple of years already with no progress...

**Comment by adamhsparks** [comment]
I'm also wont to edit things in Neovim or Zed from time to time, so I'm for sure not wedded to RStudio for the workflow here.

**Comment by rogerssam** [comment]
Agreed to keep separate.
